export const ROUTE_CONSTANTS = Object.freeze({
    HOME: '/home',
    LOGIN: '/login',
    SIGNUP: '/signUp',
    FORGOT_PASSWORD: '/forgotPassword',
    BLACK_SERIES: '/black-series',
    VIDEO_GAMES: '/video-games',
    ADMIN: '/admin',
    READ_CONTACT_ME: '/read-contact-me',
    ABOUT_ME: '/aboutMe',
    HOW_TO: '/howTo',
    FUTURE_PLANS: '/futurePlans',
    TOS: '/termsOfService',
    CONTACT_ME: '/contactMe',
});