export const STRING_CONSTANTS = Object.freeze({
    HEADER: {
        TITLE: 'SW Collection 2187',
        BUTTONS: {
            LOGIN: 'Login',
            SIGN_UP: 'Sign Up',
            LOGOUT: 'Logout',
            HOME: 'Home',
            PROFILE: 'Profile',
            BS: 'Black Series 6"',
            VIDEO_GAMES: 'Video Games',
            NAVIGATION: 'Navigation',
            ADMIN: 'Admin',
        },
        AUTH: {
            LOGIN: 'Login',
            SIGN_UP: 'Sign Up',
            LOG_IN: 'LogIn',
            FORGOT_PW: 'Forgot password?',
            HAVE_ACCOUNT: 'Already have an account? Sign in',
            PASSWORD_DONT_MATCH: 'Passwords do not match',
            INVALID_EMAIL: 'Invalid Email Address',
            RESET_PASSWORD: 'Reset Password',
            RESET_PASSWORD_LINK: 'Request Reset Link',
            BACK_TO_LOGIN: 'Back to Login?',
            DIVIDER: '─────────  or  ─────────',
            DONT_HAVE_AN_ACCOUNT: 'Don‘t have an account?',
            HUMAN: 'Please verify you are a human',
            FIELD_LABELS: {
                EMAIL: 'Email',
                PASSWORD: 'Password',
                CONFIRM_PASSWORD: 'Confrim Password',
                REMEMBER_ME: 'Remember me',
            },
        },
    },
    PAGES: {
        HOME_PAGE: {
            TITLE: 'Home',
            WELCOME: 'Hello There!',
            TAG_LINE: 'Digitally organize your Star Wars collection!',
            INTRO_PARAGRAPH_GENERIC: [
                'Do you love Star Wars? Do you collect everything Star Wars related?',
                'Do you keep track of your collection? Do you want to keep track of your collection?...',
                'Then you\'re in the right spot!',
            ].join('\n'),
            INTRO_PARAGRAPH: [
                'Do you love the Black Series? Do you collect Black Series Figures?',
                'Do you keep track of your collection? Do you want to keep track of your collection?...',
                'Then you\'re in the right spot!',
            ].join('\n'),
            HOW_IT_WORKS: 'How it works',
            GET_STARTED: 'Let\'s get started',
            CARDS: {
                BLACK_SERIES: {
                    TITLE: 'Black Series 6"',
                    BODY: 'View and add to your collection!',
                },
                VINTAGE_COLLECTION: {
                    TITLE: 'Vintage Collection',
                    BODY: 'View and add to your collection!',
                },
                VIDEO_GAMES: {
                    TITLE: 'Video Games',
                    BODY: 'View and add to your collection!',
                },
                USER_PROFILE: {
                    TITLE: 'User profile',
                    BODY: 'View ...',
                },
                ADMIN: {
                    TITLE: 'Administartion',
                    BODY: 'View, Edit, Create ...',
                },
                ABOUT_ME: {
                    TITLE: 'About Me',
                    BODY: 'Learn...',
                },
                STEP_1: {
                    TITLE: 'Step 1',
                    BODY: 'Join the Rebellion [Create an account]',
                },
                STEP_2: {
                    TITLE: 'Step 2',
                    BODY: 'Search for figures by name, year, assortment, movie, etc...',
                },
                STEP_3: {
                    TITLE: 'Step 3',
                    BODY: 'Click "Add to Collection" under figure',
                },
            },
            FOOTER: {
                ABOUT_ME: 'About Me',
                CONTACT: 'Contact Me',
                FUTURE_PLANS: 'Future Plans',
                HOW_TO: 'How To',
                TOS: 'Terms of Service',
            },
        },
        ABOUT: {
            HEADER: 'About Me',
            HEADER_SNES: 'First item in my collection',
        },
        HOW_TO: {
            TITLE: 'How to ...',
            ADD_TO_HOME_SCREEN_SCENE: {
                TITLE: 'Add to homescreen like an app [on iOS]',
                STEP_1: 'Step 1: In Safair [on iOS device]',
                STEP_2: 'Step 2: Scroll down to "Add to Homescreen"',
                STEP_3: 'Step 3: Name your "App"',
                STEP_4: 'Step 4: Move to desired location',
            },
        },
        FUTURE_PLANS: {
            TITLE: 'Future Plans',
            LIST: {
                TITLE: 'Future Plans for the Site',
                
                ABOUT: [
                    'I want this site to be the ultimate Star Wars collector site.',
                    'Which means more than just action figure lines.',
                    'Here are the collections I am looking to add in the future as of now.',
                    'Feel free to check in periodically, to see what\'s coming next or send me a message about what you\'d like to see next.',
                ].join('\n'),
                BLACK_SERIES: 'Add 6" Black Series Collection',
                VIDEO_GAMES: 'Add Star Wars Video Games',
                MOVIES: 'Add Star Wars Movies',
                BLACK_SERIES_LIGHT_SABERS: 'Add Black Series Lightsabers',
                MICRO_MACHINES_ACTION_FLEET: 'Add Action Fleet Collection',
                POWER_OF_THE_FORCE: 'Add Power of the Force Collection',
                STAR_WARS_LEGO: 'Add Star Wars Lego Sets',
                VINTAGE_COLLECTION: 'Add Vintage Collection',
                VINTAGE_FIGURES: 'Add Vintage Figures',
            },
        },
        ACTION_FIGURES: {
            TITLE: 'Action Figures',
        },
        BLACK_SERIES_CATALOG: {
            ACTION_FIGURE_DETAILS: {
                LABELS: {
                    ASSORTMENT: 'Assortment',
                    ASSORTMENT_NUMBER: '#',
                    AVERAGE_BUY_PRICE: 'Avg Buy Price',
                    CHARACTER_DETAILS_HEADER: 'Character Details',
                    COLLECTORS_DETAILS_HEADER: 'Collector Details',
                    EXCLUSIVE_RETAILER: 'Exclusive Retailer',
                    MORE_ASSORTMENT: assortment => `from [${assortment}] `,
                    MORE_SIMILAR_FIGURE: name => `More ${name} Figures`,
                    MULTIPACK: 'Part of Multipack',
                    MULTIPACK_FIGURE: 'Multipack Figures',
                    NEW_IN_BOX_QUANTITY: 'New in Box Qty',
                    OPEN_COMPLETE_QUANTITY: 'Open (complete) Qty',
                    OPEN_INCOMPLETE_QUANTITY: 'Open (incomplete) Qty',
                    PACKAGE_TYPE: 'Package Type',
                    PREORDER: 'Preordered',
                    RELEASE_DETAILS_HEADER: 'Release Details',
                    RETAILERS: 'Retailers',
                    RETAIL_PRICE: 'Retail Price',
                    SELLABLE: 'Sellable',
                    SOURCE: 'Source/First Apperance',
                    SOURCE_TYPE: 'Source Type',
                    TOTAL_OWNED: 'Total Owned',
                    TOTAL_INVESTED: 'Total Invested',
                    TRADEABLE: 'Tradeable',
                    WAVE: 'Wave',
                    YEAR: 'Year',
                },
            },
            BUTTON: {
                ALL: 'View All Again',
                RECENT: 'Newly Added',
                STATS: 'Stats',
            },
            CARDS: {
                BUTTONS: {
                    ADD: 'Add to Collection',
                    REMOVE: 'Remove',
                },
                LABELS: {
                    TOTAL_OWNED: 'Total Owned',
                    VERSION: 'Version',
                },
            },
            DISPLAY_MODAL: {
                BUTTONS: {
                    CLEAR: 'Clear Filters',
                    CLOSE: 'Save & Close',
                    IN_BOX: 'In Box Image',
                    LARGE_FIGURE: 'Large Figure',
                    OUT_OF_BOX: 'Out of Box Image',
                    SMALL_FIGURE: 'Small Figure',
                    NO_LOOSE_IMAGE: 'Missing Loose Image',
                    NO_NEW_IMAGE: 'Missing New Image',
                    NO_NUMBER: 'Missing Number',
                },
                HEADER: 'Filter / Sort / Display',
                LABELS: {
                    CHARACTERS: 'Characters',
                    DISPLAY: 'DISPLAY:',
                    GROUPS: 'Groups',
                    FILTER: 'FILTER:',
                    NOT_OWNED: 'Not Owned Figures',
                    OWNED: 'Owned Figures',
                    SORT: 'SORT:',
                    SORTING: 'Sorting',
                    VIEW_ALL: 'View All',

                },
            },
            STAT_TABLE: {
                COLUMNS: ['Source', 'Count', 'Percentage', 'Retail Cost'],
                TOTAL: 'Total',
            },
            SEARCH: 'Search by name…',
            TITLE: 'Black Series',
        },
        VIDEO_GAME_CATALOG: {
            TITLE: 'Video Games',
            DETAILS: {
                LABELS: {
                    CONSOLE: 'Systems/Consoles',
                    DEVELOPER: 'Launch Developer',
                    FORMAT: 'Launch Format',
                    PRICE: 'Launch Price',
                    RELEASE_DETAILS_HEADER: 'Release Details',
                    SERIES: 'Game Series',
                    TYPE: 'Genre',
                    YEAR: 'Launch Year',
                },
            },
        },
        VINTAGE_COLLECTION_CATALOG: {
            TITLE: 'Vintage Collection',
        },
        UPLOAD_IMAGE: {
            TITLE: 'Upload Image',
        },
        MY_COLLECTION: {
            TITLE: 'My Collection',
        },
        ADMIN: {
            BUTTON: {
                ADD: 'Add',
                DISPLAY_TABLES: 'Display Tables',
                HIDE_TABLES: 'Hide Tables',
                NEW_BLACK_SERIES: 'New BS/VC Figures',
                NEW_VIDEO_GAME: 'New Video Game',
                NEW_SOURCE: 'New Source',
                UPLOAD: 'Upload',
            },
            IMAGE_FILE_LOCATION: 'File available at:',
            INPUT_VALUE: 'Value',
            LABELS: {
                ASSORTMENT: 'assortment',
                DATA_TYPE: 'dataType',
                SERIES: 'series',
            },
            NEW_COLLECTION_FORM: {
                HEADER: 'Feed the Database!',
                LABELS: {
                    ADD_NAME_DETAILS: { KEY: 'Additional Name Details', VALUE: 'additionalNameDetails' },
                    ASSORTMENT: { KEY: 'Assortment', VALUE: 'assortment' },
                    COLLECTION_TYPE: { KEY: 'Collection Type', VALUE: 'collectionType' },
                    EXCLUSIVE_RETAILER: { KEY: 'Exclusive Retailer', VALUE: 'exclusiveRetailer' },
                    LOOSE_BLACK_IMAGE: { KEY: 'Loose Black Image', VALUE: 'name' },
                    LOOSE_IMAGE: { KEY: 'Loose Image', VALUE: 'looseImageUrl' },
                    MULTIPACK: { KEY: 'Multipack', VALUE: 'multipack' },
                    NAME: { KEY: 'Name', VALUE: 'name' },
                    NIB_IMAGE: { KEY: 'NIB Image', VALUE: 'newImageUrl' },
                    PACKAGE_TYPE: { KEY: 'Package Type', VALUE: 'packageType' },
                    RETAIL_PRICE: { KEY: 'Retail Price', VALUE: 'retailPrice' },
                    SERIES: { KEY: 'Series', VALUE: 'series' },
                    SERIES_NUMBER: { KEY: 'Series Number', VALUE: 'seriesNumber' },
                    SOURCE_MATERIAL: { KEY: 'Source Material', VALUE: 'sourceMaterial' },
                    SOURCE_TYPE: { KEY: 'Source Type', VALUE: 'sourceType' },
                    VERSIONS: { KEY: 'Versions', VALUE: 'version' },
                    WAVE: { KEY: 'Wave', VALUE: 'wave' },
                    YEAR: { KEY: 'Year', VALUE: 'year' },
                },
            },
            NEW_VIDEO_GAME_FORM: {
                HEADER: 'Feed the Database!',
                LABELS: {
                    COLLECTION_TYPE: { KEY: 'Collection Type', VALUE: 'collectionType' },
                    CONSOLE: { KEY: 'Consoles', VALUE: 'console' },
                    DEVELOPER: { KEY: 'Developer', VALUE: 'developer' },
                    ICON: { KEY: 'Icon Type', VALUE: 'iconName' },
                    IMAGE: { KEY: 'Image', VALUE: 'imageUrl' },
                    NAME: { KEY: 'Name', VALUE: 'name' },
                    PRICE: { KEY: 'Price', VALUE: 'price' },
                    VIDEO_GAME_FORMAT: { KEY: 'Format', VALUE: 'videoGameFormat' },
                    VIDEO_GAME_SERIES: { KEY: 'Series', VALUE: 'videoGameSeries' },
                    VIDEO_GAME_TYPE: { KEY: 'Type', VALUE: 'videoGameType' },
                    YEAR: { KEY: 'Year', VALUE: 'year' },
                },
            },
            TABLE_DETAILS: 'These tables populate the form inputs:',
            TITLE: 'Administration',
        },
        CONTACT_ME: {
            LABELS: {
                EMAIL: 'Email',
                CATEGORY: 'Category',
                FIRST_NAME: 'First Name',
                LAST_NAME: 'Last Name',
                MESSAGE: 'Message',
            },
            SUCCESS: 'Thanks, message recevied!',
            TITLE: 'Contact Me',
            CATEGORYS: [
                'Bug/Issue - Please Fix',
                'Enhancement Idea',
                'How to ...',
                'Mislabeled Item',
                'Request to add to collection',
                'Other...',
            ],
        },
        READ_CONTACT_ME: {
            TITLE: 'Read Messages Sent to Me',
        },
        TERMS_OF_SERVICE: {
            TITLE: 'Terms of Service',
        },
        USER_PROFILE:{
            TITLE: 'User Profile',
            SECTION_TITLES: {
                COLLECTION_TOTALS: 'Collection Totals',

            },
            TABLE_COL: {
                COLLECTION_TYPE: 'Type',
                PRODUCT_LINE: 'Product Line',
                COUNT: '# Owned',
                COST: 'Cost',
                TOTAL: 'Total',
            },
        },
    },
    GENERAL: {
        BUTTON: {
            SUBMIT: 'Submit',
            CONTINUE: 'Continue',
            DONE: 'Done',
            MY_COLLECTION: 'My Collection',
            ALL: 'View All Again',
            RECENT: 'Newly Added',
            STATS: 'Stats',
        },
        MENU_ITEMS: {
            NONE: 'none',
        },
        FILTER_MODAL: {
            BUTTONS: {
                CLEAR: 'Clear Filters',
                CLOSE: 'Save & Close',
                IN_BOX: 'In Box Image',
                LARGE_FIGURE: 'Large Figure',
                OUT_OF_BOX: 'Out of Box Image',
                SMALL_FIGURE: 'Small Figure',
            },
            HEADER: 'Filter / Sort / Display',
            LABELS: {
                CHARACTERS: 'Characters',
                DISPLAY: 'DISPLAY:',
                GROUPS: 'Groups',
                FILTER: 'FILTER:',
                NOT_OWNED: 'Not Owned Figures',
                OWNED: 'Owned Figures',
                SORT: 'SORT:',
                SORTING: 'Sorting',
                VIEW_ALL: 'View All',
            },
        },
    },
});