import { STRING_CONSTANTS } from 'shared/constants/stringConstants';

export const HEADER_BUTTONS = STRING_CONSTANTS.HEADER.BUTTONS;
export const HEADER_TITLE = STRING_CONSTANTS.HEADER.TITLE;
export const AUTH = STRING_CONSTANTS.HEADER.AUTH;

export const PAGES = STRING_CONSTANTS.PAGES;

export const HOME_PAGE = STRING_CONSTANTS.PAGES.HOME_PAGE;
export const HOME_PAGE_TITLE = STRING_CONSTANTS.PAGES.HOME_PAGE;
export const HOME_PAGE_CARDS = STRING_CONSTANTS.PAGES.HOME_PAGE.CARDS;

export const USER_PROFILE = STRING_CONSTANTS.PAGES.USER_PROFILE;

export const ADMIN = STRING_CONSTANTS.PAGES.ADMIN;
export const NEW_COLLECTION_FORM = ADMIN.NEW_COLLECTION_FORM;

export const GENERAL = STRING_CONSTANTS.GENERAL;

export const STAT_TABLE = STRING_CONSTANTS.PAGES.BLACK_SERIES_CATALOG.STAT_TABLE;