export const STRING_CONSTANTS = Object.freeze({
    HEADER: {
        TITLE: 'SW Collection 2187',
        BUTTONS: {
            LOGIN: 'Login',
            SIGN_UP: 'Sign Up',
            LOGOUT: 'Logout',
            HOME: 'Home',
        },
        AUTH: {
            LOGIN: 'Login',
            SIGN_UP: 'Sign Up',
            LOG_IN: 'LogIn',
            FORGOT_PW: 'Forgot password?',
            NO_ACCOUNT: 'Don\'t have an account? Sign Up',
            HAVE_ACCOUNT: 'Already have an account? Sign in',
            PASSWORD_DONT_MATCH: 'Passwords do not match',
            INVALID_EMAIL: 'Invalid Email Address',
            RESET_PASSWORD: 'Reset Password',
            RESET_PASSWORD_LINK: 'Request Reset Link',
            BACK_TO_LOGIN: 'Back to Login?',
            DIVIDER: '───────────── OR ────────────',
            DONT_HAVE_AN_ACCOUNT: 'Don\'t have an account? Sign Up',
            FIELD_LABELS: {
                EMAIL: 'Email',
                PASSWORD: 'Password',
                CONFIRM_PASSWORD: 'Confrim Password',
                REMEMBER_ME: 'Remember me',
            },
        },
    },
    PAGES: {
        HOME_PAGE: {
            TITLE: 'Home',
            WELCOME: 'Hello There!',
            TAG_LINE: 'Digitally organize your Star Wars collection!',
            INTRO_PARAGRAPH_GENERIC: [
                'Do you love Star Wars? Do you collect everything Star Wars related?',
                'Do you keep track of your collection? Do you want to keep track of your collection?...',
                'Then you\'re in the right spot!',
            ].join('\n'),
            INTRO_PARAGRAPH: [
                'Do you love the Black Series? Do you collect Black Series Figures?',
                'Do you keep track of your collection? Do you want to keep track of your collection?...',
                'Then you\'re in the right spot!',
            ].join('\n'),
            HOW_IT_WORKS: 'How it works',
            GET_STARTED: 'Let\'s get started',
            CARDS: {
                BLACK_SERIES: {
                    TITLE: 'Black Series Catalog',
                    BODY: 'View and add to your collection!',
                },
                VIDEO_GAMES: {
                    TITLE: 'Video Games Catalog',
                    BODY: 'View and add to your collection!',
                },
                USER_PROFILE: {
                    TITLE: 'User profile',
                    BODY: 'View ...',
                },
                ADMIN: {
                    TITLE: 'Administartion',
                    BODY: 'View, Edit, Create ...',
                },
                ABOUT_ME: {
                    TITLE: 'About Me',
                    BODY: 'Learn...',
                },
                STEP_1: {
                    TITLE: 'Step 1',
                    BODY: 'Join the Rebellion [Create an account]',
                },
                STEP_2: {
                    TITLE: 'Step 2',
                    BODY: 'Search for figures by name, year, assortment, movie, etc...',
                },
                STEP_3: {
                    TITLE: 'Step 3',
                    BODY: 'Click "Add to Collection" under figure',
                },
            },
            FOOTER: {
                ABOUT_ME: 'About Me',
                CONTACT: 'Contact Me',
                FUTURE_PLANS: 'Future Plans',
                HOW_TO: 'How To',
                TOS: 'Terms of Service',
            },
        },
        ABOUT: {
            HEADER: 'About Me',
            HEADER_INTRO: 'Where it all started...',
            INTRO: [
                'I have been a Star Wars fan ever since my I was about 5 years old.' ,
                'My dad "needed" to buy us a SNES and the first game he bought with it was Super Star Wars: The Empire Strikes back.',
                'I had a blast playing the game.',
                'However, I was still reluctant to watch the movies, but a father [occasionally] knows best and he finally sat me down to watch A New Hope.',
                'The rest they say "is history", as I feel in love with it all.',
                'Thus started my collecting of all things Star Wars!',
            ].join('\n'),
            HEADER_WHY: 'Why create this space?',
            WHY: [
                'Having collected for over 25 years now I\'ve amassed a pretty decent collection.',
                'And although I know about 99% of everything I have, there are times I could use some sort of reference so I don\'t buy duplicates.',
                '(Unless I\'m trying to army build, then buy all the duplicate troopers!)',
                'There are a ton of sites that offer an archive/current database list of available collectibles.',
                'However, none of them let me keep track of which of those I own.',
                'Combined that with my career as a software engineer, it only seemed reasonable to fix my own problem and then share with other fans',
            ].join('\n'),
            HEADER_START: 'Starting with The Black Series',
            STARTING: [
                'I decided to start with the Black Series collection.',
                'I enjoy collecting these figures, it\'s an active series and I think they deserve big images to show off how great they look (well most of them).',
                'I plan to venture into the 3 3/4" figures next, once I fix some bugs and add a few more features.',
            ].join('\n'),
            HEADER_SNES: 'First item in my collection',
            HEADER_TBS_COLLECTION: 'My Black Series Collection',
            TBS_COLLECTION: [
                '*Like most collectors (I\'ll assume) I struggle with the choice of opening each figure or not...',
            ].join('\n'),
        },
        HOW_TO: {
            TITLE: 'How to ...',
            ADD_TO_HOME_SCREEN_SCENE: {
                TITLE: 'Add to homescreen like an app [on iOS]',
                STEP_1: 'Step 1: In Safair [on iOS device]',
                STEP_2: 'Step 2: Scroll down to "Add to Homescreen"',
                STEP_3: 'Step 3: Name your "App"',
                STEP_4: 'Step 4: Move to desired location',
            },
        },
        FUTURE_PLANS: {
            TITLE: 'Future Plans',
            LIST: {
                TITLE: 'Future Plans for the Site',
                
                ABOUT: [
                    'I want this site to be the ultimate Star Wars collector site.',
                    'Which means more than just action figure lines.',
                    'Here are the collections I am looking to add in the future as of now.',
                    'Feel free to check in periodically, to see what\'s coming next or send me a message about what you\'d like to see next.',
                ].join('\n'),
                BLACK_SERIES: 'Add 6" Black Series Collection',
                VIDEO_GAMES: 'Add Star Wars Video Games',
                MOVIES: 'Add Star Wars Movies',
                BLACK_SERIES_LIGHT_SABERS: 'Add Black Series Lightsabers',
                MICRO_MACHINES_ACTION_FLEET: 'Add Action Fleet Collection',
                POWER_OF_THE_FORCE: 'Add Power of the Force Collection',
                STAR_WARS_LEGO: 'Add Star Wars Lego Sets',
                VINTAGE_COLLECTION: 'Add Vintage Collection',
                VINTAGE_FIGURES: 'Add Vintage Figures',
            },
        },
        BLACK_SERIES_CATALOG: {
            ACTION_FIGURE_DETAILS: {
                LABELS: {
                    ASSORTMENT: 'Assortment',
                    ASSORTMENT_NUMBER: '#',
                    CHARACTER_DETAILS_HEADER: 'Character Details',
                    COLLECTORS_DETAILS_HEADER: 'Collector Details',
                    EXCLUSIVE_RETAILER: 'Exclusive Retailer',
                    MORE_ASSORTMENT: assortment => `from [${assortment}] `,
                    MORE_SIMILAR_FIGURE: name => `More ${name} Figures`,
                    MULTIPACK: 'Part of Multipack',
                    MULTIPACK_FIGURE: 'Multipack Figures',
                    NEW_IN_BOX_QUANTITY: 'New in Box Qty',
                    OPEN_COMPLETE_QUANTITY: 'Open (complete) Qty',
                    OPEN_INCOMPLETE_QUANTITY: 'Open (incomplete) Qty',
                    PACKAGE_TYPE: 'Package Type',
                    RELEASE_DETAILS_HEADER: 'Release Details',
                    RETAIL_PRICE: 'Retail Price',
                    SOURCE: 'Source/First Apperance',
                    TOTAL_OWNED: 'Total Owned',
                    WAVE: 'Wave',
                    YEAR: 'Year',
                },
            },
            BUTTON: {
                ALL: 'View All Again',
                RECENT: 'Newly Added',
                STATS: 'Stats',
            },
            CARDS: {
                BUTTONS: {
                    ADD: 'Add to Collection',
                    REMOVE: 'Remove from Collection',
                },
                LABELS: {
                    TOTAL_OWNED: 'Total Owned',
                    VERSION: 'Version',
                },
            },
            DISPLAY_MODAL: {
                BUTTONS: {
                    CLEAR: 'Clear Filters',
                    CLOSE: 'Save & Close',
                    IN_BOX: 'In Box Image',
                    LARGE_FIGURE: 'Large Figure',
                    OUT_OF_BOX: 'Out of Box Image',
                    SMALL_FIGURE: 'Small Figure',
                },
                HEADER: 'Filter / Sort / Display',
                LABELS: {
                    CHARACTERS: 'Characters',
                    DISPLAY: 'DISPLAY:',
                    GROUPS: 'Groups',
                    FILTER: 'FILTER:',
                    NOT_OWNED: 'Not Owned Figures',
                    OWNED: 'Owned Figures',
                    SORT: 'SORT:',
                    SORTING: 'Sorting',
                    VIEW_ALL: 'View All',

                },
            },
            STAT_TABLE: {
                COLUMNS: ['Source', 'Count', 'Percentage', 'Retail Cost'],
                TOTAL: 'Total',
            },
            SEARCH: 'Search by name…',
            TITLE: 'Black Series Catalog',
        },
        VIDEO_GAME_CATALOG: {
            TITLE: 'Video Games',
            DETAILS: {
                LABELS: {
                    CONSOLE: 'Systems/Consoles',
                    DEVELOPER: 'Developer',
                    FORMAT: 'Launch Format',
                    PRICE: 'Launch Price',
                    RELEASE_DETAILS_HEADER: 'Release Details',
                    SERIES: 'Game Series',
                    TYPE: 'Genre',
                    YEAR: 'Year',
                },
            },
        },
        UPLOAD_IMAGE: {
            TITLE: 'Upload Image',
        },
        MY_COLLECTION: {
            TITLE: 'My Collection',
        },
        ADMIN: {
            BUTTON: {
                ADD: 'Add',
                DISPLAY_TABLES: 'Display Tables',
                HIDE_TABLES: 'Hide Tables',
                NEW_BLACK_SERIES: 'New Black Series',
                NEW_VIDEO_GAME: 'New Video Game',
                UPLOAD: 'Upload',
            },
            IMAGE_FILE_LOCATION: 'File available at:',
            INPUT_VALUE: 'Value',
            LABELS: {
                ASSORTMENT: 'assortment',
                DATA_TYPE: 'dataType',
            },
            NEW_COLLECTION_FORM: {
                HEADER: 'Feed the Database!',
                LABELS: {
                    ADD_NAME_DETAILS: { KEY: 'Additional Name Details', VALUE: 'additionalNameDetails' },
                    ASSORTMENT: { KEY: 'Assortment', VALUE: 'assortment' },
                    COLLECTION_TYPE: { KEY: 'Collection Type', VALUE: 'collectionType' },
                    EXCLUSIVE_RETAILER: { KEY: 'Exclusive Retailer', VALUE: 'exclusiveRetailer' },
                    LOOSE_BLACK_IMAGE: { KEY: 'Loose Black Image', VALUE: 'name' },
                    LOOSE_IMAGE: { KEY: 'Loose Image', VALUE: 'looseImageUrl' },
                    MULTIPACK: { KEY: 'Multipack', VALUE: 'multipack' },
                    NAME: { KEY: 'Name', VALUE: 'name' },
                    NIB_IMAGE: { KEY: 'NIB Image', VALUE: 'newImageUrl' },
                    PACKAGE_TYPE: { KEY: 'Package Type', VALUE: 'packageType' },
                    RETAIL_PRICE: { KEY: 'Retail Price', VALUE: 'retailPrice' },
                    SERIES: { KEY: 'Series', VALUE: 'series' },
                    SERIES_NUMBER: { KEY: 'Series Number', VALUE: 'seriesNumber' },
                    SOURCE_MATERIAL: { KEY: 'Source Material', VALUE: 'sourceMaterial' },
                    SOURCE_TYPE: { KEY: 'Source Type', VALUE: 'sourceType' },
                    VERSIONS: { KEY: 'Versions', VALUE: 'version' },
                    WAVE: { KEY: 'Wave', VALUE: 'wave' },
                    YEAR: { KEY: 'Year', VALUE: 'year' },
                },
            },
            NEW_VIDEO_GAME_FORM: {
                HEADER: 'Feed the Database!',
                LABELS: {
                    COLLECTION_TYPE: { KEY: 'Collection Type', VALUE: 'collectionType' },
                    CONSOLE: { KEY: 'Consoles', VALUE: 'console' },
                    DEVELOPER: { KEY: 'Developer', VALUE: 'developer' },
                    ICON: { KEY: 'Icon Type', VALUE: 'iconName' },
                    IMAGE: { KEY: 'Image', VALUE: 'imageUrl' },
                    NAME: { KEY: 'Name', VALUE: 'name' },
                    PRICE: { KEY: 'Price', VALUE: 'price' },
                    VIDEO_GAME_FORMAT: { KEY: 'VG Format', VALUE: 'videoGameFormat' },
                    VIDEO_GAME_SERIES: { KEY: 'VG Series', VALUE: 'videoGameSeries' },
                    VIDEO_GAME_TYPE: { KEY: 'VG Type', VALUE: 'videoGameType' },
                    YEAR: { KEY: 'Year', VALUE: 'year' },
                },
            },
            TABLE_DETAILS: 'These tables populate the form inputs:',
            TITLE: 'Administration',
        },
        CONTACT_ME: {
            LABELS: {
                EMAIL: 'Email',
                CATEGORY: 'Category',
                FIRST_NAME: 'First Name',
                LAST_NAME: 'Last Name',
                MESSAGE: 'Message',
            },
            SUCCESS: 'Thanks, message recevied!',
            TITLE: 'Contact Me',
            CATEGORYS: [
                'Bug/Issue - Please Fix',
                'Enhancement Idea',
                'How to ...',
                'Mislabeled Item',
                'Request to add to collection',
                'Other...',
            ],
        },
        TERMS_OF_SERVICE: {
            TITLE: 'Terms of Service',
        },
    },
    GENERAL: {
        BUTTON: {
            SUBMIT: 'Submit',
            CONTINUE: 'Continue',
            DONE: 'Done',
        },
        MENU_ITEMS: {
            NONE: 'none',
        },
    },
});